config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :hellos
  root "hellos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hello.rb
class Hello < ApplicationRecord
	mount_uploader :file_location
	validates_presence_of :title, :date, :description, :file_location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hellos_controller.rb
class HellosController < ApplicationController
	before_action :set_photo, :only => [:show, :edit, :update,:destroy]
	def index
		@hellos = Hello.all
	end

	def new
		@hello = Hello.new
	end

	def create
		@hello = Hello.new(hello_params)
		if @hello.save

		redirect_to hellos_url
	else
		 render :action => :new
		end
		
	end

	def show
		
		
	end

	def edit
		
		
	end

	def update
		
		if @hello.update_attributes(hello_params)

		redirect_to hellos_path
	    else
	    	render :action => :new
	    end

		
	end

	def destroy
		
		@hello.destroy

		redirect_to hellos_path
		
	end

	def set_photo
		@hello = Hello.find(params[:id])
	end

	private

	def hello_params
		params.require(:hello).permit(:title, :date, :description, :file_location)
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hellos_helper.rb
module HellosHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/hellos/_form.html.erb
<div class="form container">
<%= form_for @hello do |f| %>
<div class="form-group">
  <%= f.label :title, "Title"  %>
  <%= f.text_field :title ,class:"form-control"%>
</div>

<div class="form-group">
  <%= f.label :date, "Date" %>
  <%= f.text_field :date ,class:"form-control"%>
</div>

<div class="form-group">
  <%= f.label :description, "Description" %>
  <%= f.text_area :description,class:"form-control" %>
</div>

<div class="form-group">
  <%= f.label :file_location, "File Location" %>
  <%= f.file_field :file_location %>
</div>

  <%= f.submit %>
<% end %>
</div>


<% if @hello.errors.present? %>
  <ul>
    <% @hello.errors.each do |error, message| %>
      <li> <%= "#{error.capitalize}  #{message}" %></li>
    <% end %>
  </ul>
<% end %>

app/views/hellos/edit.html.erb
<%= render :partial => "form" %>

app/views/hellos/index.html.erb
<table class="table table-striped">
 <% @hellos.each do |photo| %>
   <tr>
    <td> <%= photo.title %></td> 
     <td> <%= link_to 'Show', hello_path(photo) %></td> 
     <td> <%= link_to 'Edit', edit_hello_path(photo) %></td> 
     <td> <%= link_to 'Destroy', hello_path(photo), method: :delete, data:{ confirm: "Are you sure?" } %></td> 
   </tr>
 <% end %>
</table>

<%= link_to 'New Photo', new_hello_path %>

app/views/hellos/new.html.erb
<%= render :partial => "form" %>

app/views/hellos/show.html.erb
<style>
  h2{color:green;}
  .form-group{
  	color:blue;
  	font-size:15pt;
  	margin-left:100px;
  	padding:0px 20px;
    
  }
</style>


<div class="container">
<div class="form-group">
<%= @hello.title %>
<h2>we are the world</h2>
</div>


<div class="form-group">
<%= @hello.date %>
</div>

<div class="form-group">
<%= image_tag @hello.file_location.url ,size:"300x300",class:"img-thumbnail" %>
</div>

<div class="form-group">
<%= simple_format(@hello.description) %>
</div>

<div class="form-group">
<%= link_to 'Back to index', hellos_path %>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserAlbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>